---
# build os/arch for gox
build:
  - darwin/386
  - darwin/amd64
  - linux/386
  - linux/amd64
  - linux/arm
  - windows/amd64
  # doesn't compile
  #- android/arm
releases:
  # yaml keys must match the git tag
  v0.6.3-rc1:
    name: "docopts binary transitional v0.6.3-rc1"
    description: |
      This is a transitional release.

      It supports all the previous API plus some extra command line options.
      Fully compatible with previous 0.6.2 python code for Bash.
      See: https://github.com/docopt/docopts/tree/v0.6.1%2Bfix

      based on master branch

      changes:
        - more test for MACOS
        - bash 3.2 support is more documented and fixed
        - use bats-core as testing framework
        - updated README merged from old README.rst
        - now documentation introduce `docopts.sh` See [docs](https://github.com/docopt/docopts/tree/v0.6.3-rc1/docs/)
        - added Makefile
        - added build_doc.sh PoC markdown preprocessor

      all examples written for docopts:
        - shebang conversion `#!/bin/bash` ==> `#!/usr/bin/env bash`
        - legacy example completed
        - example from README extracted a file, and merged in README via build_doc.sh
        - sshdiff full example coded
        - added examples with `--auto -G`

      docopts.sh helper:
        - is more documented in the code
        - as a documenation in [docs/README.md](https://github.com/docopt/docopts/tree/v0.6.3-rc1/docs/README.md)
        - now supports bash strict mode (`set -euo pipefail`)
        - now supports `--auto -G` to auto parse with global vars (doesn't use bash 4 associative array)

      `docopts` behavior sould be unchanged:
        - add mangled name collision detection

  v0.6.3-alpha1:
    name: "docopts for Bash first release in golang"
    description: |
      This is a transitional release. It is a complete rewrite of the python's code in go.
      It supports all the previous API plus some extra command line options.

      Fully compatible with previous 0.6.2 python code for Bash.

      based on https://github.com/docopt/docopts/tree/packaging-debian

  v0.6.2:
    name: "first release in Go"
    description: |
      This is a transitional release.

      Dopopt for shell.

      It supports all the previous API.
      Fully compatible with previous 0.6.1 python code for Bash.
      See: https://github.com/docopt/docopts/tree/v0.6.1%2Bfix

      based on master branch

      changes:
        - now written in Go, no more python dependancy
      
